### ISSUE TITLE
sidebar obscures content area

### ISSUE THREAD

**Issue by normkatz** [InfyOmLabs/laravel-generator#223]
In my generated CRUD web pages with your bootstrap template, the sidebar, when visible obscures a chunk of the left side of the page on desktop browsers such as Chrome and FF. I would expect it to push the content window to the right as the sidebar slides in during its transition to visible. Is this a known bug and if so, is there a fix planned? I could not find it in the github issues.
![sidebar](https://cloud.githubusercontent.com/assets/2975757/16720524/1db13982-46ec-11e6-902a-3421292a2a71.png)

**Comment by phillipmadsen** [comment]
I  have also had this problem and I  have a fix I will push today.

**Comment by phillipmadsen** [comment]
I  have pushed them but if you need them sooner you can find them here

https://github.com/InfyOmLabs/core-templates/pull/40
https://github.com/InfyOmLabs/core-templates/pull/39

**Comment by mitulgolakiya** [comment]
@phillipmadsen @normkatz I merged it. Can you try it with the latest code ?

**Comment by normkatz** [comment]
ok, i'll try today

**Comment by phillipmadsen** [comment]
Let me know if I need to check it out if not fixed. Thnx

**Comment by matheusmmo** [comment]
I tried with the new changes but the problem persists.

So I added a offset-3 and made a pull request. If anyone can merge, it will help others https://github.com/InfyOmLabs/core-templates/pull/41

Thanks

**Comment by mitulgolakiya** [comment]
@matheusmmo @phillipmadsen just merged it.

**Comment by normkatz** [comment]
Yeah, didn't get back to you yesterday but I had recorded a video showing
that the header was pushing to the right on window expand when the left
menu would appear but not the content section.  I will try this one now and
confirm.

**Comment by normkatz** [comment]
attached are 2 pics, before and after.  Before shows the small window
without the left menu.  After shows how the menu appears but content is
obscured because it did not push right (like it would on a typical mobile
app).  Still not working after merge.  Tested with both Safari and Chrome
on OSX.

**Comment by mitulgolakiya** [comment]
@normkatz check with the latest version. It should work now.

**Comment by normkatz** [comment]
did not work for me.  In fact the behavior of the black left panel is
erratic when you change the width of the browser window from small to very
large.  I'm not really using the tool anymore so it's not a priority for
me.  But thanks for looking into this.

Norm
